### ISSUE TITLE
Error: Cannot find module 'mmap'

### ISSUE THREAD

**Issue by naholyr** [bnoordhuis/node-mmap#6]
After `npm install mmap`, `require("mmap")` throws this.

The issue is that the `mmap.node` file has been built in `build/Release` instead of the expected `build/default` found in package.json.

I think it comes from node's version: cf nodester/nodester#264

**Comment by bnoordhuis** [comment]
Thanks for the report. It's fixed in 9918f30. I've uploaded v0.0.4 to npm.
